"""Builds website/ from the last demo run."""
from __future__ import annotations
import pathlib
from . import sitekit as sk

ROOT = pathlib.Path(__file__).resolve().parent.parent
META = {
    "name": "Optimization Under Uncertainty",
    "slug": "optimization-under-uncertainty",
    "repo": "4.0-Decision-Intelligence-Framework",
    "pillar": "Cross-cutting — the endeavor itself",
    "tagline": "Deterministic, sample-average, CVaR and robust formulations of the "
               "same allocation problem — fitted in-sample, judged out-of-sample, in "
               "portfolio allocation and hospital staffing.",
    "tags": [("SAA", ""), ("CVaR LP", ""), ("box-robust", ""),
             ("out-of-sample", ""), ("synthetic scenarios", "demo")],
    "banner": "Scenarios are generated by src/problems.py, deliberately as mixtures "
              "with crash and surge regimes: on Gaussian data every method here would "
              "score identically and the comparison would be empty. Every method is "
              "fitted on one sample and scored on a different, larger one.",
}


def build_site(results: dict) -> pathlib.Path:
    p, s = results["portfolio"], results["staffing"]
    sw = results["scenario_sweep"]
    best = min(p["out_of_sample"], key=lambda k: p["out_of_sample"][k]["cvar"])

    metrics = sk.metric_grid([
        ("Best out-of-sample CVaR", f"{p['out_of_sample'][best]['cvar']:.4f}", best),
        ("Scenarios", f"{p['n_train']} → {p['n_test']:,}", "train → test"),
        ("Staffing budget", f"{s['budget']:.0f}", f"{s['n_units']} units"),
        ("Demand correlation", f"{s['surge_is_common']:.2f}", "across units"),
    ])

    port_tbl = sk.table(
        ["Method", "Mean loss", "CVaR-90", "Worst case", "Concentration",
         "Mean regret", "% best"],
        [[k, f"{v['mean']:.4f}", f"{v['cvar']:.4f}", f"{v['worst']:.4f}",
          f"{p['concentration'][k]:.3f}", f"{p['regret'][k]['mean_regret']:.4f}",
          f"{p['regret'][k]['frac_best']:.1%}"]
         for k, v in p["out_of_sample"].items()],
        numeric_cols=(1, 2, 3, 4, 5, 6))

    cvar_chart = sk.bar_chart(
        [(k, v["cvar"]) for k, v in p["out_of_sample"].items()], fmt="{:.4f}")

    opt_tbl = sk.table(
        ["Method", "In-sample CVaR", "Out-of-sample CVaR", "Optimism"],
        [[r["method"], f"{r['in_sample_cvar']:.4f}", f"{r['out_of_sample_cvar']:.4f}",
          f"{r['optimism']:+.4f}"] for r in results["optimism"]],
        numeric_cols=(1, 2, 3))

    sweep_chart = sk.line_chart(
        [("CVaR method", [(r["n_train"], r["cvar_method_oos_cvar"])
                          for r in sw["rows"]]),
         ("SAA method", [(r["n_train"], r["saa_method_oos_cvar"])
                         for r in sw["rows"]])],
        xlabel="training scenarios", ylabel="out-of-sample CVaR-90")

    staff_tbl = sk.table(
        ["Method", "In-sample CVaR", "Out-of-sample CVaR", "Mean cost",
         "Unmet rate", "Shifts fully covered"],
        [[k, f"{s['in_sample'][k]['cvar']:.1f}", f"{v['cvar']:.1f}",
          f"{v['mean']:.2f}", f"{s['service'][k]['unmet_rate']:.1%}",
          f"{s['service'][k]['shifts_fully_covered']:.1%}"]
         for k, v in s["out_of_sample"].items()],
        numeric_cols=(1, 2, 3, 4, 5))

    body = f"""
<section>
  <h2>Four ways to be wrong about the future</h2>
  <div class="stack">
    <p>All four formulations solve the same allocation problem and differ only in what
    they optimise against: the mean scenario, the average across sampled scenarios, the
    worst tail, or an adversarially chosen parameter inside an uncertainty set. Two
    problems, because a bad decision costs different things — money in one, unmet
    clinical demand in the other, and the second is not symmetric with over-provision.</p>
    <p>Every method is fitted on one scenario sample and scored on a different, larger
    one. That split is the whole discipline: a stochastic program evaluated on the
    scenarios it optimised over reports its own objective back to itself.</p>
  </div>
</section>

<section>
  <h2>This run</h2>
  <div class="stack-lg">
    {metrics}
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      generated {sk.esc(results['generated_at'])} &middot;
      {p['n_assets']} assets &middot; {s['n_units']} hospital units &middot;
      unmet demand penalised {s['unmet_penalty']:.0f}× idle capacity
    </p>
  </div>
</section>

<section>
  <h2>Portfolio allocation — CVaR wins</h2>
  <div class="stack-lg">
    {cvar_chart}
    {port_tbl}
    <p>The CVaR formulation gives the lowest tail loss, the lowest worst case,
    <em>and</em> the highest mean return, at a concentration well below the
    deterministic solution. That combination is not guaranteed and is worth stating
    plainly: on this generator, protecting the tail cost nothing.</p>
    {opt_tbl}
    <p>Optimism is how much each method flatters itself when scored on the sample it was
    fitted to. Equal weighting fits nothing and so has almost none
    ({results['optimism'][-1]['optimism']:+.4f}); every optimised method has more. That
    column is the argument for the out-of-sample split, made with the numbers rather
    than asserted.</p>
  </div>
</section>

<section>
  <h2>The bug that looked like a finding</h2>
  <div class="stack-lg">
    <div class="note">
      <h3>Pure CVaR minimisation put everything in two assets</h3>
      <p>The first version of the CVaR portfolio had no position limit. It scored
      <em>worse out of sample than equal weighting</em>, with a concentration of 1.000.
      The obvious diagnosis was tail overfitting — CVaR-90 estimates its objective from
      the worst 10% of the training sample, which at 600 scenarios is 60 points.</p>
      <p>That diagnosis was wrong, and the sweep below is what ruled it out. If the
      problem were sample size, the disadvantage would shrink as the sample grew. It did
      not: at 6,400 scenarios the gap was unchanged and concentration was still above
      0.97. The cause was the formulation. Minimising CVaR over a simplex is a linear
      program, and a linear program's optimum sits at a vertex, so the solver has no
      reason to hold more than a handful of assets.</p>
      <p>Adding a return target did not fix it either, because the concentrated solution
      already had the highest expected return and the constraint never bound. What was
      missing is a position limit — which every real mandate carries. With one, CVaR
      becomes the best method on the board.</p>
    </div>
    {sweep_chart}
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      Sweep re-run with the position limit in place; CVaR now beats SAA at every sample
      size, by {abs(sw['rows'][0]['gap']):.3f} to {abs(sw['rows'][3]['gap']):.3f} CVaR.
    </p>
  </div>
</section>

<section>
  <h2>Hospital staffing — CVaR loses, for a structural reason</h2>
  <div class="stack-lg">
    {staff_tbl}
    <div class="note">
      <h3>The CVaR plan solved its objective and still lost</h3>
      <p>Read the first two numeric columns together. The CVaR plan has the
      <strong>best in-sample</strong> tail cost ({s['in_sample']['CVaR-90']['cvar']:.1f},
      better than both alternatives) and the <strong>worst out-of-sample</strong> tail
      cost ({s['out_of_sample']['CVaR-90']['cvar']:.1f}). It optimised exactly what it
      was asked to and the answer did not transfer.</p>
      <p>The reason is in the last metric on this page: mean pairwise demand correlation
      across units is <strong>{s['surge_is_common']:.2f}</strong>. The surge is a
      <em>common</em> shock — an epidemic or a mass-casualty event hits every unit at
      once — and no reallocation of a <em>fixed</em> budget can hedge a common shock.
      The CVaR plan pays for tail protection it cannot deliver, and the payment shows up
      as a worse mean.</p>
      <p>This is the opposite of the portfolio result and for a precise reason. There,
      correlation rises in the crash regime but stays below 1, so diversification still
      buys something. Here it does not. The lesson is not "CVaR is good" or "CVaR is
      bad" — it is that tail-focused allocation helps only when the tail risk is
      partly idiosyncratic, and the honest answer to a common shock is a bigger budget,
      not a cleverer split of the one you have.</p>
    </div>
  </div>
</section>

<section>
  <h2>Reproduce it</h2>
  <div class="stack">
    <pre>cd optimization-under-uncertainty
pip install -r requirements.txt
python -m pytest tests/ -q
python -m src.demo</pre>
    <p>Solvers use scipy's <code>linprog</code> and SLSQP so the repository has no
    modelling-language dependency. That caps problem size, and a production version
    belongs in cvxpy or Pyomo.</p>
  </div>
</section>

<section>
  <h2>What this does not establish</h2>
  <div class="stack">
    <ul class="tight">
      <li>Both problems are synthetic. The generators were written by the same person as
      the solvers, and the conclusions are about those generators.</li>
      <li>The staffing result depends on how much of the surge is common across units.
      A hospital whose demand shocks are unit-specific would show the opposite.</li>
      <li>The robust formulation uses a box uncertainty set with a closed-form inner
      maximisation. Ellipsoidal and budgeted sets behave differently and are not
      implemented.</li>
      <li>No transaction costs, no rebalancing, no multi-period dynamics. Single-period
      allocation only.</li>
      <li>Staffing treats nurses as divisible and interchangeable. Real rostering has
      integrality, skill mix and shift-pattern constraints.</li>
    </ul>
  </div>
</section>
"""
    return sk.build(ROOT, META, body, results)
